### ISSUE TITLE
Getting animated plots in Shiny

### ISSUE THREAD

**Issue by ramnathv** [cpsievert/pitchRx#2]
I saw your post on the Shiny Google group. I took a closer look at your code for the animation in `inst/shiny/server.R` and I think there is a bug. If you look at [these lines](https://github.com/cpsievert/pitchRx/blob/master/inst/shiny/server.R#L126-L134), you realize that you are using `ani.start()`, which changes the working directory to a temporary directory where the HTML file is stored. 

An easy fix is to use `saveHTML` so that you can control where it is getting saved, and then insert it as an `iframe`. This would be the cleanest way of doing it without having to write extra code.

If you want to render the animation directly on the page, you will have to add the `scianimator` files to your page, and then print the generated javascript, a little bit more roundabout, but doable.

Hope this helps.

**Comment by cpsievert** [comment]
animint provides a nice framework for producing animations. I finally got some PITCHf/x animation in a shiny app [here](http://104.131.111.111:3838/pitchRx2/) ([see here](https://github.com/cpsievert/shiny_apps/tree/master/pitchRx2) for source)
