### ISSUE TITLE
 Illegal characters found in URL

### ISSUE THREAD

**Issue by thevorpalblade** [cpsievert/pitchRx#28]
When running
scrape(start = "2007-04-01", end = "2007-04-30", connect=mydb)
I get the output:
If file names don't print right away, please be patient.
Error in function (type, msg, asError = TRUE)  : 
  Illegal characters found in URL
> 

However:
scrape(start = "2008-04-01", end = "2008-04-30", connect=mydb)  
works with no errors.

**Comment by cpsievert** [comment]
PITCHf/x data isn't available before 2008.

**Comment by thevorpalblade** [comment]
I'm pretty sure it is, though. Here's some from 4/6/2007:

http://gd2.mlb.com/components/game/mlb/year_2007/month_04/day_06/gid_2007_04_06_arimlb_wasmlb_1/inning/

**Comment by cpsievert** [comment]
Those are x/y locations, not PITCHf/x. This won't work for reasons similar to #25.
