### ISSUE TITLE
Scrape function goes to debugger when connect argument is used

### ISSUE THREAD

**Issue by ntw5292** [cpsievert/pitchRx#35]
When using the scrape command with the connect argument, the debugger pops up and highlights "browser" on line 9 of the code used to write the scrape function. Here's the code I'm using:

devtools::install_github("pitchRx","cpsievert")
library(pitchRx)
library(dplyr)
library(RMySQL)
my_db <- src_sqlite("pitchRx.sqlite3",create=TRUE)
conn <- dbConnect(MySQL(),username='root',password='password',dbname='pitchRx')
a <- scrape(start="2015-05-02",end="2015-05-02")
b <- scrape(start="2015-05-02",end="2015-05-02",connect=my_db$con)
c <- scrape(start="2015-05-02",end="2015-05-02",connect=conn)

The line without the connect argument works fine. I'm using R 3.2.1 on OS X Yosemite 10.10.3, and the version of MySQL i have is 5.6.26.

**Comment by cpsievert** [comment]
Thanks!
